### ISSUE TITLE
不开全局代理 访问国内网站很卡是什么原因呢?

### ISSUE THREAD

**Issue by Nza6920** [pigpigchacha/publicmsg#2]
访问百度都要好几秒才打得开, 开了全局则不会

**Comment by pigpigchacha** [comment]
> 访问百度都要好几秒才打得开, 开了全局则不会

所有都慢还是只有百度慢？

**Comment by Nza6920** [comment]
> > 访问百度都要好几秒才打得开, 开了全局则不会
> 
> 所有都慢还是只有百度慢？

呃.. 好像只有百度慢

**Comment by pigpigchacha** [comment]
那应该是百度服务器不稳定，有的时候，我这边有也这种情况，似乎是百度的cdn有时不给力啊

**Comment by Nza6920** [comment]
> 那应该是百度服务器不稳定，有的时候，我这边有也这种情况，似乎是百度的cdn有时不给力啊
好吧

**Comment by pigpigchacha** [comment]
> > 那应该是百度服务器不稳定，有的时候，我这边有也这种情况，似乎是百度的cdn有时不给力啊
> > 好吧
 
这边确实找到一个关于百度的问题，已经修复了，今日更新
