### ISSUE TITLE
2024年开始就极其不稳定

### ISSUE THREAD

**Issue by arrosev** [pigpigchacha/publicmsg#8]
这玩意以前不止稳定而且很快，我也是好几年老用户了，从这个软件刚出就开始用了，那时候还有注册就送流量的活动，从今年开始，经常性连不上，不止是延迟变高了，现在连客服都联系不上了，我主要是拿来google找资料和下一些开发环境，以前碰到问题，找客服都是秒回的，也会远程帮你解决问题。现在就。。实在忍受不了，我寻思就算服务器炸了，客服也发个公告说下吧，不然谁知道你是不是跑了。

**Comment by toyydsBT123** [comment]
你也炸了？我刚刚一登发现也炸了，问客服没有消息

**Comment by TeppoEvans** [comment]
节点又炸了，刚续费的季卡

**Comment by KNIGHTOFYURI** [comment]
win直接炸了，登录显示网络请求出错，但是好像ios勉强还能用

**Comment by Prismoven** [comment]
ios也炸了

**Comment by Prismoven** [comment]
奇怪，我先开其他加速器，然后就能打开pigcha
随后关闭其他加速器，pigcha就恢复了正常

这个状态维持了两个小时，很稳定

**Comment by TraderWagon** [comment]
彻底跑路了

**Comment by arrosev** [comment]
> 奇怪，我先开其他加速器，然后就能打开pigcha 随后关闭其他加速器，pigcha就恢复了正常
> 
> 这个状态维持了两个小时，很稳定

为什么我不行

**Comment by JohnZhang3IoT** [comment]
什么节点也看不到

**Comment by easycoderxp** [comment]
boom

**Comment by Mercy-TH** [comment]
怎么节点看不到了呀

**Comment by andyxue1688** [comment]
没有人修复了吗？一个节点都没有了，登录也登录不上了。

**Comment by GUILTYxC** [comment]
这种东西就是容易突然暴毙跑路，每次只敢充一个月

**Comment by AndyCodyLiu** [comment]
所以现在谁有别的梯子啊啊啊啊啊啊

**Comment by TraderWagon** [comment]
> 所以现在谁有别的梯子啊啊啊啊啊啊

目前为止我用过最好的梯子，播放Youtube、Netflix 高清视频从未如此轻松。

下载链接（推荐使用 Chrome 浏览器访问）：https://bitbucket.org/letsgo666/letsgogo_1/src/main/README.md

备用链接（推荐使用 Chrome 浏览器访问）：https://github.com/LetsgoNetwork/LetsGo_1/blob/main/

安装后打开填写我的ID：352206392 你能多得3天会员！

**Comment by Prismoven** [comment]
> 奇怪，我先开其他加速器，然后就能打开pigcha 随后关闭其他加速器，pigcha就恢复了正常
> 
> 这个状态维持了两个小时，很稳定

不对，这个不行
这个现象的本质是我那台设备没有退出pigcha登录

只要是还处于登录状态的设备就可以使用这个方法
但是退出就没办法了

我描述一下我遇到的现象：
1、windows机器：pigcha无法登录
2、windows机器：开启clash再关闭后pigcha功能恢复正常，但杀掉pigcha进程后再打开就无法登录了
3、ubuntu机器：这台机器一直保持pigcha登录状态，一直能正常使用，我正在用它发布这条评论

**Comment by aqiang1** [comment]
是不是跑路了

**Comment by utaware** [comment]
客服不回公告没有，持续时间也不短了，不合适吧

**Comment by yangzheng-git** [comment]
我有一台windows设备，一直保持登录状态，现在还可用。另一台windows未保持登录，现在不可用了。感觉像是用于管理的服务器挂掉了，负责加速和代理的服务器还ok

**Comment by JohnZhang3IoT** [comment]
还有其他推荐吗，可以过渡一下的

**Comment by hujiaqing789** [comment]
你2023年好歹也会发公告 2024年开始你怎么就开始走下坡路了？你别这样阿 我刚开了一年的卡，大哥。

**Comment by MutouRenMe** [comment]
这么久还没恢复

**Comment by 646373491** [comment]
我刚开了两年啊，大哥，不会就这样不明不白用不了了吧

**Comment by KNIGHTOFYURI** [comment]
按理说不至于这样玩失踪，不会是被gank了吧

**Comment by chenqi13814529300** [comment]
我也炸了，只有保持登录的机子还可以用，完了

**Comment by dszpr** [comment]
用了四五年了。。从来没有过这次这种崩的时间长+没有公告+客服不回的情况，不会真的要跑路了吧TvT

**Comment by AmosPO** [comment]
我上个月才充了一年,现在突然boom了,让人崩溃

**Comment by zhaoleon** [comment]
估计跑路了

**Comment by ResourceTemplar** [comment]
去年受人推荐开始用，一口气续费到明年七月二号，这就黄了？再也不敢贪便宜充太久了，新加速器我也一次只充一个月好了

**Comment by jingerKXR** [comment]
我的也炸了，服了

**Comment by Mowar** [comment]
跑路了嘛

**Comment by AlopexLagopusXu** [comment]
跑路了吧，一点反应都没有

**Comment by SaKura-0225** [comment]
前段时间也出现过这样的情况，一晚左右好了，现在都一天多了还没好

**Comment by againpretender** [comment]
有点过分了，公告也不发一个，这是真跑路了？

**Comment by luolaizhong** [comment]
犹豫了好久充了一年卡，刚用了不到一个月，就这样了。Windows电脑登不上了，用不了，但iPhone手机虽然登录不上，可以在设置里打开VPN开关，还是可以用。唉，只能用来偶尔刷刷X，看看国外新闻了。

**Comment by LamChiho** [comment]
+1，还有好起来的希望吗QAQ，我才充了一年的啊

**Comment by MrKSeven** [comment]
现在还是不行，真润了这是

**Comment by AmosPO** [comment]
我7月份充了一年，现在突然不行了，内心崩溃

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月05日 15:28 |
| 收件人 | pigpigchacha/publicmsg ***@***.***> |
| 抄送人 | ams-aa ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [pigpigchacha/publicmsg] 2024年开始就极其不稳定 (Issue #8) |

现在还是不行，真润了这是

**Comment by lzyerlzyer** [comment]
卧槽了，刚开了一年的卡就没了嘛

**Comment by KNIGHTOFYURI** [comment]
寄了，ios也没了

**Comment by A1exy** [comment]
淦 windows和ios都登不上了

**Comment by helianthushhh** [comment]
> 所以现在谁有别的梯子啊啊啊啊啊啊

https://invite.xlcc.live?code=376445 ## 飞鸟加速 注册立即获得免费时长30分钟，绑定我的邀请码(376445)额外赠送免费时长30分钟这个可以试试，也挺干净的

**Comment by Estrella-Explore** [comment]
应该是跑路了

**Comment by yeshunlong** [comment]
难受，刚充了钱

**Comment by Jiang-321** [comment]
刚续了费，网页客服和微信客服都不回消息，估计跑路了，用了一年多了，真的是

**Comment by yjm020811** [comment]
没gpt没法上班了啊

**Comment by alexosng** [comment]
我刚冲完，第二天，就跑路啊，账号都无法登录。。。

**Comment by Estrella-Explore** [comment]
浙江温州，浙江温州，江南皮革厂，江南皮革厂，倒闭啦，倒闭啦！
老板皮个差，带着我的包年套餐，逃跑啦，逃跑啦！
________________________________
发件人: yeshunlong ***@***.***>
发送时间: 2024年9月6日 13:13
收件人: pigpigchacha/publicmsg ***@***.***>
抄送: Estrella-Explore ***@***.***>; Comment ***@***.***>
主题: Re: [pigpigchacha/publicmsg] 2024年开始就极其不稳定 (Issue #8)


难受，刚充了钱

―

**Comment by helianthushhh** [comment]
> 好像pigcha跑路了？？？哪位老铁推荐个替代品啊。。。

[https://invite.xlcc.live?code=376445](https://invite.xlcc.live/?code=376445) ## 飞鸟加速 注册立即获得免费时长30分钟，绑定我的邀请码(376445)额外赠送免费时长30分钟这个可以试试，也挺干净的  建议租短期，害怕跑路。先用一段试试水

**Comment by wangxin776** [comment]
> 刚续了费，网页客服和微信客服都不回消息，估计跑路了，用了一年多了，真的是

微信客服联系方式能给一个吗，之前一直用tg联系，后来群解散了，没法联系上了

**Comment by TraderWagon** [comment]
跑的很彻底不用想了，永远叫不醒一个装睡的人

**Comment by TraderWagon** [comment]
跑的很彻底
&nbsp;


郭瑞
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月7日(星期六) 凌晨0:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pigpigchacha/publicmsg] 2024年开始就极其不稳定 (Issue #8)














  
刚续了费，网页客服和微信客服都不回消息，估计跑路了，用了一年多了，真的是
  
微信客服联系方式能给一个吗，之前一直用tg联系，后来群解散了，没法联系上了

**Comment by lvyou1983** [comment]
> > 所以现在谁有别的梯子啊啊啊啊啊啊
> 
> 目前为止我用过最好的梯子，播放Youtube、Netflix 高清视频从未如此轻松。
> 
> 下载链接（推荐使用 Chrome 浏览器访问）：https://bitbucket.org/letsgo666/letsgogo_1/src/main/README.md
> 
> 备用链接（推荐使用 Chrome 浏览器访问）：https://github.com/LetsgoNetwork/LetsGo_1/blob/main/
> 
> 安装后打开填写我的ID：352206392 你能多得3天会员！

根本没有地方填ID啊？？？

**Comment by lvyou1983** [comment]
> > 好像pigcha跑路了？？？哪位老铁推荐个替代品啊。。。
> 
> [https://invite.xlcc.live?code=376445](https://invite.xlcc.live/?code=376445) ## 飞鸟加速 注册立即获得免费时长30分钟，绑定我的邀请码(376445)额外赠送免费时长30分钟这个可以试试，也挺干净的 建议租短期，害怕跑路。先用一段试试水

试了下，油管1080P卡的不行啊。。老铁再推荐几款试试

**Comment by duyi0922** [comment]
我也纳闷怎么进入9月份始终登陆不上去，原来是跑路了，真坑啊。

**Comment by Gentlezhy** [comment]
怎么跑路了?之前挺好使的啊我看用的人也挺多???我推广还挣了200多块钱呢..

**Comment by dcxigpi** [comment]
pc端登陆不了

**Comment by monk279** [comment]
> > 刚续了费，网页客服和微信客服都不回消息，估计跑路了，用了一年多了，真的是
> 
> 微信客服联系方式能给一个吗，之前一直用tg联系，后来群解散了，没法联系上了

都跑路了

**Comment by HM1ng** [comment]
> 这玩意以前不止稳定而且很快，我也是好几年老用户了，从这个软件刚出就开始用了，那时候还有注册就送流量的活动，从今年开始，经常性连不上，不止是延迟变高了，现在连客服都联系不上了，我主要是拿来google找资料和下一些开发环境，以前碰到问题，找客服都是秒回的，也会远程帮你解决问题。现在就。。实在忍受不了，我寻思就算服务器炸了，客服也发个公告说下吧，不然谁知道你是不是跑了。

建议试用一下这个，https://jpcdn.ts123.cc/register?code=9twT3iNO

**Comment by coder-yanMing** [comment]
今天又登录不上了，官网也打不开了

**Comment by helianthushhh** [comment]
> 今天又登录不上了，官网也打不开了

昨天能登上？

**Comment by coder-yanMing** [comment]
> > 今天又登录不上了，官网也打不开了
> 
> 昨天能登上？

不好意思，昨天休息天，没试，不过前段时间也有这种情况，不过一天左右好像就好了，另外还给了补偿，我是买的流量那种，送了我3个G流量，如果是包月的话可能会送几天吧，这。。。这两天看情况吧

**Comment by wangshengwangsheng** [comment]
> > > 今天又登录不上了，官网也打不开了
> > 
> > 
> > 昨天能登上？
> 
> 不好意思，昨天休息天，没试，不过前段时间也有这种情况，不过一天左右好像就好了，另外还给了补偿，我是买的流量那种，送了我3个G流量，如果是包月的话可能会送几天吧，这。。。这两天看情况吧

已经快一周了吧？

**Comment by shi01485** [comment]
还是不行啊 现在

**Comment by yangtao2o** [comment]
这种情况就需要多备几个了 现在用的这个[三毛机场](https://a.smjcdh.com/#/register?code=3xdChn8t) 几块钱一个月 好几块就可以一年 可以试试
